package model.hibernate;
// Generated 12-feb-2018 13:40:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Directores generated by hbm2java
 */
public class Directores implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String apellidos;
    private String pais;
    private Set peliculases = new HashSet(0);

    public Directores() {
    }

    public Directores(Integer id, String nombre, String apellidos, String pais) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.pais = pais;
    }

    public Directores(Integer id, String nombre, String apellidos, String pais, Set peliculases) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.pais = pais;
        this.peliculases = peliculases;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public Set getPeliculases() {
        return this.peliculases;
    }

    public void setPeliculases(Set peliculases) {
        this.peliculases = peliculases;
    }

}
