package model.hibernate;
// Generated 12-feb-2018 13:40:12 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

    private Integer id;
    private Directores directores;
    private String tituloPelicula;
    private String descripcion;
    private Date fechaPublicacion;
    private int duracion;
    private String paisPublicacion;
    //private int tiempoAlquiler;
    private float notaUsuarios;
    private float notaPrensa;
    private boolean esSerie;
    //private Series series;
    private Set generoses = new HashSet(0);

    public Peliculas() {
    }

    public Peliculas(Integer id, Directores directores, String tituloPelicula, Date fechaPublicacion, int duracion, String paisPublicacion, float notaUsuarios, float notaPrensa, boolean esSerie) {
        this.id= id;
        this.directores = directores;
        this.tituloPelicula = tituloPelicula;
        this.fechaPublicacion = fechaPublicacion;
        this.duracion = duracion;
        this.paisPublicacion = paisPublicacion;
        //this.tiempoAlquiler = tiempoAlquiler;
        this.notaUsuarios = notaUsuarios;
        this.notaPrensa = notaPrensa;
        this.esSerie = esSerie;
    }

    public Peliculas(Integer id,Directores directores, String tituloPelicula, String descripcion, Date fechaPublicacion, int duracion, String paisPublicacion, float notaUsuarios, float notaPrensa, boolean esSerie, Set generoses) {
        this.id= id;
        this.directores = directores;
        this.tituloPelicula = tituloPelicula;
        this.descripcion = descripcion;
        this.fechaPublicacion = fechaPublicacion;
        this.duracion = duracion;
        this.paisPublicacion = paisPublicacion;
        //this.tiempoAlquiler = tiempoAlquiler;
        this.notaUsuarios = notaUsuarios;
        this.notaPrensa = notaPrensa;
        this.esSerie = esSerie;
        //this.series = series;
        this.generoses = generoses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Directores getDirectores() {
        return this.directores;
    }

    public void setDirectores(Directores directores) {
        this.directores = directores;
    }

    public String getTituloPelicula() {
        return this.tituloPelicula;
    }

    public void setTituloPelicula(String tituloPelicula) {
        this.tituloPelicula = tituloPelicula;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    public int getDuracion() {
        return this.duracion;
    }

    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    public String getPaisPublicacion() {
        return this.paisPublicacion;
    }

    public void setPaisPublicacion(String paisPublicacion) {
        this.paisPublicacion = paisPublicacion;
    }

    /*public int getTiempoAlquiler() {
        return this.tiempoAlquiler;
    }

    public void setTiempoAlquiler(int tiempoAlquiler) {
        this.tiempoAlquiler = tiempoAlquiler;
    }*/

    public float getNotaUsuarios() {
        return this.notaUsuarios;
    }

    public void setNotaUsuarios(float notaUsuarios) {
        this.notaUsuarios = notaUsuarios;
    }

    public float getNotaPrensa() {
        return this.notaPrensa;
    }

    public void setNotaPrensa(float notaPrensa) {
        this.notaPrensa = notaPrensa;
    }

    public boolean isEsSerie() {
        return this.esSerie;
    }

    public void setEsSerie(boolean esSerie) {
        this.esSerie = esSerie;
    }

    /*public Series getSeries() {
        return this.series;
    }

    public void setSeries(Series series) {
        this.series = series;
    }*/

    public Set getGeneroses() {
        return this.generoses;
    }

    public void setGeneroses(Set generoses) {
        this.generoses = generoses;
    }

}
