package model.hibernate;
// Generated 08-feb-2018 21:48:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Series generated by hbm2java
 */
public class Series  implements java.io.Serializable {


     private int idPelicula;
     private Peliculas peliculas;
     private int numCaps;
     private int estado;
     private Date fechaFin;

    public Series() {
    }

	
    public Series(Peliculas peliculas, int numCaps, int estado) {
        this.peliculas = peliculas;
        this.numCaps = numCaps;
        this.estado = estado;
    }
    public Series(Peliculas peliculas, int numCaps, int estado, Date fechaFin) {
       this.peliculas = peliculas;
       this.numCaps = numCaps;
       this.estado = estado;
       this.fechaFin = fechaFin;
    }
   
    public int getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public int getNumCaps() {
        return this.numCaps;
    }
    
    public void setNumCaps(int numCaps) {
        this.numCaps = numCaps;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


