package model.hibernate;
// Generated 12-feb-2018 13:40:12 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

    private int idPelicula;
    private Peliculas peliculas;
    private int numCaps;
    private String estado;
    private Date fechaFin;

    public Series() {
    }
    
    public Series(int idPelicula, Peliculas peliculas, int numCaps, String estado, Date fechaFin) {
        this.idPelicula = idPelicula;
        this.peliculas = peliculas;
        this.numCaps = numCaps;
        this.estado = estado;
        this.fechaFin = fechaFin;
    }

    public int getIdPelicula() {
        return this.idPelicula;
    }

    public void setIdPelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }

    public Peliculas getPeliculas() {
        return this.peliculas;
    }

    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }

    public int getNumCaps() {
        return this.numCaps;
    }

    public void setNumCaps(int numCaps) {
        this.numCaps = numCaps;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

}
